name: 'Quallio : Upload Sarif'
description: 'Upload scanning analysis results to Quallio'
author: 'Quallio'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'upload-cloud'
  color: 'orange'

# Define your inputs here.
inputs:
  sarif_file:
    description:
      'The SARIF file or directory of SARIF files to be uploaded to Quallio'
    required: false
    default: '../results'
  # api_key:
  #   description: 'Quallio API key'
  #   required: true
  #   type: string
  # checkout_path:
  #   description: "The path at which the analyzed repository was checked out. Used to relativize any absolute paths in the uploaded SARIF file."
  #   required: false
  #   default: ${{ github.workspace }}
  # ref:
  #   description: "The ref where results will be uploaded. If not provided, the Action will use the GITHUB_REF environment variable. If provided, the sha input must be provided as well. This input is ignored for pull requests from forks."
  #   required: false
  # sha:
  #   description: "The sha of the HEAD of the ref where results will be uploaded. If not provided, the Action will use the GITHUB_SHA environment variable. If provided, the ref input must be provided as well. This input is ignored for pull requests from forks."
  #   required: false
  # token:
  #   description: "GitHub token to use for authenticating with this instance of GitHub. The token must be the built-in GitHub Actions token, and the workflow must have the `security-events: write` permission. Most of the time it is advisable to avoid specifying this input so that the workflow falls back to using the default value."
  #   required: false
  #   default: ${{ github.token }}
  # category:
  #   description: String used by Code Scanning for matching the analyses
  #   required: false
  # wait-for-processing:
  #   description: If true, the Action will wait for the uploaded SARIF to be processed before completing.
  #   required: true
  #   default: "true"

# Define your outputs here.
outputs:
  sarif-id:
    description: 'The ID of the SARIF file uploaded to Quallio'

runs:
  using: node20
  main: dist/index.js
